[package]
name = "jacktrip-rust"
version = "0.3.0"
authors = ["tom <tomward@fmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.6"
